### PR TITLE
(v2.1) NETKET_USE_LAPACK=OFF by default

### PR DESCRIPTION
**Pull request by PhilipVinc**
Compilation with Lapack is broken due to lapack
see https://gist.github.com/PhilipVinc/e8c3b7449ffbe7ee8afd5b71b3b75aae

### CODE REVIEW

**Comment by twesterhout** [comment]
I don't think this is the correct approach. Intel MKL is pretty amazing. There are at least two ways to resolve your compilation error:
* Remove unnecessary `#include`s and play around with `#include` order.
* `#undef I` in appropriate places in source (`.cc`) files. Example: https://godbolt.org/z/AGNXWe.

I'd prefer the first solution, but it's more work.

**Comment by gcarleo** [comment]
OK, I tend to agree with @twesterhout , I also think that @fabienalet did something similar to the second solution suggested, but I am not sure how hard this is in the newer version of NetKet?

**Comment by PhilipVinc** [comment]
I also agree, but as of now pip-installing version 2.1 will fail on default behavior on (most people’s) laptop.
When eventually this failure is fixed, we can quickly revert this.

—

I’ll have a look at your first proposal but I’m not sure it’s going to be that easy...
Il 31 gen 2020, 20:23 +0100, Giuseppe Carleo <notifications@github.com>, ha scritto:

**Comment by gcarleo** [comment]
OK I agree that this PR should seen as a bug fix, thus we can merge it. For the other solutions we will need more time

**Comment by fabienalet** [comment]
I indeed [did](https://github.com/netket/netket/issues/113) something similar. I'll try to take a look later if something similar can be done, but I agree that this can be done at a later stage.

**Pull request merged**
