### PR TITLE
[fix] unique atom coordinates fixed. Closes #547

### LINKED ISSUE #547: Uniqueness check in lattice.py is faulty
Lines 145-146 of `graph/lattice.py` do not work the intended way, as np.unique flattens the array even when turned into a list of tuples. They should be replaced with
```python
uniques = _np.unique(atoms_coord, axis=0)
```
which selects the unique rows of the array.

### PR DESCRIPTION
**Pull request by VolodyaCO**
This is just a patch that solves #547

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Thanks!
Could you also add a test to cover it while you’re at it?

**Comment by VolodyaCO** [comment]
Done @PhilipVinc

**Comment by gcarleo** [comment]
why **all** tests are failing?

**Review by gcarleo — APPROVED** [review]

**Comment by PhilipVinc** [comment]
It's the nk3 branch.
After implementing the fix of Dian, I have seen more failures... To investigate

**Pull request merged**
