### PR TITLE
V2.1

### PR DESCRIPTION
**Pull request by gcarleo**
# Summary for version 2.1

This version is a direct follow-up of version 2.0, refining and improving several aspects of the transition undergone when shifting to being a python library built on c++ primitives. This version also includes several new functionalities and improves installation on common platforms (including conda). 

## New functionalities 

1. Support for open quantum systems, including various density matrix ansatz states, and solvers for the stationary Lindblad equation @PhilipVinc. 
2. Add support for PyTorch machines @nikita-astronaut @twesterhout 
3. Progress bar for VMC drive @orialb
4. Separate the SR driver as a standalone optimizer @femtobit 
5. Make J and use of sign rule configurable for Heisenberg Hamiltonian @femtobit 
6. Add batched samplers @twesterhout @gcarleo @femtobit 

## Library changes 
1. Introduce python abstract classes for Machines and Samplers @gcarleo 
2. Added a few numba kernels for performance @gcarleo 
3. Support for conda installs
4. Move to a simpler solution for documentation @gcarleo 
5. Write most high-level drivers in pure python @femtobit @gcarleo @PhilipVinc 
6. Add some code documentation for RBMs @amitkumarj441  
7. Expose a to_array method for Python machines @tvieijra 
8. Start removing look-up table logic in machines @twesterhout 

## Known issues
- Windows is not supported

### CODE REVIEW

**Comment by gcarleo** [comment]
I have drafted some release notes up here, I am sure I have forgot something, so please update it if you see that your work on this version is not mentioned! 

Thanks everybody!

**Comment by PhilipVinc** [comment]
Looks good. 
I'd merge for now. this is branch that was good already.
In a few days if everything is good we can tag a v2.1 release

**Comment by femtobit** [comment]
Agreed.

**Comment by gcarleo** [comment]
OK please approve this then and we can merge ! @PhilipVinc if you can add a conda recipe to this it would be good, otherwise we keep it for 3.0

**Comment by PhilipVinc** [comment]
I'll make a pr directly on master if you want, but I don't see the point.

To make a conda recipe you first must tag a release on GitHub. 
Until we tag a release the Conda-build mechanism cannot really work...
Once this is done, the conda recipe should be sent to Conda-forge.

**Pull request merged**
