### PR TITLE
Make Jastrow kernel symmetric

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by gcarleo** [comment]
@femtobit or @wdphy16 if you know a better way to only use half of the parameters and work with symmetric matrices it would be amazing

**Comment by femtobit** [comment]
Should `W` be symmetric or Hermitian for complex parameters?

**Comment by gcarleo** [comment]
just symmetric

**Comment by femtobit** [comment]
@gcarleo It is possible to only store the upper triangular part of `W` and build the full matrix in `__call__`. I've tried this here:
https://github.com/netket/netket/blob/37e8ce0a3e646993d0ee9dcf9a9c642df2043d62/netket/models/jastrow.py#L24-L63

There is a performance overhead, though it doesn't look too bad (at least for `N=32` spins):
```
# W + W.T symmetrization
14 µs ± 657 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
# triu
18.8 µs ± 695 ns per loop (mean ± std. dev. of 7 runs, 100000 loops each)
```

**Comment by gcarleo** [comment]
nice @femtobit, it's true that there is some small overhead but maybe it is still better when computing gradients, since we only have half the parameters...  maybe we can implement your solution instead of the transpose trick?

**Comment by PhilipVinc** [comment]
Is there a pathological case we could check for which one works best?

**Comment by gcarleo** [comment]
let's merge this for now and we'll get back to this once more urgent things have been addressed

**Review by gcarleo — APPROVED** [review]

**Pull request merged**
