### PR TITLE
Fix samples SRt

### PR DESCRIPTION
**Pull request by riccardo-rende**
Fix samples bug in `netket.experimental.driver.VMC_SRt`.

We have also added `UnoptimalSRtWarning`.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@riccardo-rende you should run ruff and black, all pre commit checks.

To do this, you should install dev dependencies (`pip install -e '.[dev]') then `pre-commit install`
and this should ensure that your future commits are ok.

To fix past formatting errors, just `pre-commit run --all-files`

**Comment by gcarleo** [comment]
more info here https://netket.readthedocs.io/en/latest/docs/contributing.html#contributing-code-using-pull-requests

**Comment by riccardo-rende** [comment]
I did it

**Review by PhilipVinc — APPROVED** [review]
I changed the test to properly cover the case where `n_samples != n_chains` and also check that this warning is raised. Otherwise that's good to go if tests pass

**Pull request merged**
