### PR TITLE
Implement Schmitt's regularisation for TDVP

### PR DESCRIPTION
**Pull request by PhilipVinc**
This PR Implements the SNR regulariser by Markus Schmitt and Heyl (https://journals.aps.org/prl/abstract/10.1103/PhysRevLett.125.100503). 

The implementation works and has been tested in the last few weeks by several persons, however I'm not happy with the interface of this (namely, having a different driver). 

Probably we would need to create some sort of 'preconditioner' interface for the regularisation we want to use, but for now I think this is good enough and would benefit from being shipped in NetKet

cc @markusschmitt

### CODE REVIEW

**Comment by PhilipVinc** [comment]
This has been tested 'well enough' by a few users so I am merging it.

**Comment by gcarleo** [comment]
what about the test failing?

**Comment by PhilipVinc** [comment]
It's a test that randomly fails from time to time on that runner (that uses the oldest dependencies we claim to support), and it was on a code-path not touched by this PR. 
It's not  relevant

**Comment by attila-i-szabo** [comment]
Note for later: nothing about this regulariser is specific for TDVP, we should develop a QGT class based on `QGTJacobianDense` that implements it for any application.

**Pull request merged**
