### PR TITLE
Remake docs

### PR DESCRIPTION
**Pull request by PhilipVinc**
With Giuseppe we were talking about refreshing the front page of the netket website to include a blog and some news section.

I would also like to refresh the documentation website to put the tutorials more in front of the eyes of users, and to be just plain out better.

This is not yet finished, but it's quite nice already. I'd like some feedback on it.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
preview link:

https://netket.readthedocs.io/en/latest/tutorials/gs-ising.html

**Comment by gcarleo** [comment]
looks like there is still some problem, for example in https://netket.readthedocs.io/en/latest/docs/operator.html ? (missing most text below and no continousoperator?)

**Comment by PhilipVinc** [comment]
Haha, that's because it's like this also in our current documentation https://www.netket.org/docs/operator.html

**Comment by PhilipVinc** [comment]
Mergin this will keep the old site up for now. 
It will just allow me to properly attach readthedocs

**Review by gcarleo — APPROVED** [review]

**Pull request merged**
