### PR TITLE
[RFC] Make MPI an Optional dependency

### PR DESCRIPTION
**Pull request by PhilipVinc**
We could argue that MPI is necessary to achieve high performance with netket, but people trying out the library for the first time, or students, possibly don't have MPI installed.

As it's not trivial to install it if you don't have admin access to your machine, or if you have an old distro (on linux), making it optional might go a long way to help them meet netket.

This PR has no functional change, as I had already made mpi4py an optional dependency long ago.
However, while on mac it is possible to install mpi4py even without mpicc compiler (though you can't load it), on linux you cannot install mpi4py without the right compilers...

What this PR does is simply remove mpi4py from the direct dependencies of netket, and slightly reword the readme in order to say that if MPI is not installed, then it won't be used.

Still, i should add a check for mpi version>=3. in the init code. 

Please let me know if you think this is a good idea or not.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
GitHub Actions CI will fail until [actions/virtual-environments#1889](https://github.com/actions/virtual-environments/pull/1889) is merged because Microsoft broke stuff...

**Comment by gcarleo** [comment]
I agree that we should not ask users to have mpi installed (also because at this stage that's the only "harder-to-install" requirement for us, and that should be opt in. But can't we have an option in setup.py to install all other optional things? (i.e., at the moment, jax and mpi, most importantly. This would also automatically
 install mpi4jax I guess...)

**Comment by gcarleo** [comment]
something like ```extras_require``` ?

**Comment by PhilipVinc** [comment]
Yeah, extras_requires is a good idea, so in the end people could do
`pip install netket`  to install netket with no other backends
`pip install netket[mpi]` to install netket and mpi4py. On linux this will only work if an mpi compiler is present 
`pip install netket[jax]` to also install the jax backend

`pip install netket[mpi,jax]` to install mpi and jax backend.

Unfortunately, it is not possible to specify mixed conditional dependencies: if both mpi and jax are specified, it's impossible to request that also 'mpi4jax' is installed... But in any case this will be covered by warnings.

**Comment by gcarleo** [comment]
ok this looks good! is there a way to do something like ```pip install netket[all]``` that installs all optional things? (including mpi4jax, for example)

**Comment by PhilipVinc** [comment]
Apparently not.

**Comment by PhilipVinc** [comment]
Though we can define ourselves an 'all' extras with all extras

**Review by gcarleo — APPROVED** [review]
yes, that looks great thanks!

**Comment by PhilipVinc** [comment]
Hmm.. maybe in ALL we should not put DEV dependencies  if it's for end users. Do you agree?

**Comment by gcarleo** [comment]
> Hmm.. maybe in ALL we should not put DEV dependencies if it's for end users. Do you agree?

yes good point... but then we need all_dev or something

**Comment by PhilipVinc** [comment]
you can always chain them, like
`pip install netket[dev,mpi,jax]` or `pip install netket[all,dev]`

**Pull request merged**
