### PR TITLE
Setting up Binder to run Tutorials

### PR DESCRIPTION
**Pull request by jamesETsmith**
This PR sets up [binder](https://mybinder.readthedocs.io/en/latest/index.html), which would allow users to run small tutorials on virtual machines hosted by binder. I mentioned it in the issue #156.

Binder uses the `environment.yml` file to set up a `Conda` environment with all of the dependencies (mpi4py, an mpicompiler, numpy, etc). I've added a badge in the `README.md` that links to the binder build of NetKet. I've tested `CustomHamiltonian.ipynb`, which runs without issue, and 'j1j2.ipynb`, which crashes when the user creates the FFNN. I'm not totally sure why this is yet, but I'll continue to look into it. 

If you want to check out the binder you can use the badge in the `README.md` or this link: https://mybinder.org/v2/gh/jamesETsmith/netket/mybinder

### CODE REVIEW

**Comment by gcarleo** [comment]
@jamesETsmith thanks! This indeed is a good idea, especially to facilitate the online workflow. I was just experiencing some issue running the second Tutorial, somehow the code was freezing when defining the `Machine`, I am not sure this is related to me or if it's an issue you see too?

**Comment by jamesETsmith** [comment]
@gcarleo that sounds like a similar problem to the one I was experiencing. You can also run terminals on binder, which actually show error messages (unlike the notebooks), and from a few quick tests on these, I think this an mpi4py/MPI problem. I will have a look at this more over the next few days!

**Comment by gcarleo** [comment]
@jamesETsmith can you try to remove mpi4py at once ? Basically we don't need it anymore, and maybe it is causing some issue... anyways if you remember, we were having issues with conda installs on Mac. We should try again now that we don't use mpi4py

**Comment by jamesETsmith** [comment]
Apologies for the delay on this, I will try to get this up and running this week so we can link to a binder notebook in the paper.

**Comment by jamesETsmith** [comment]
@gcarleo, it looks like things were already working after my last commit and I remembered incorrectly. Do you want me to close this PR and open a new one on the main branch?

**Comment by gcarleo** [comment]
Yes please!

**Pull request closed without merging**
