### PR TITLE
Updated Heisenberg1d - Now Symmetric RBM works

### PR DESCRIPTION
**Pull request by pesvut**
Fixed some small issues with the Hisenberg1d.
- Fixed the Symmetric RBM section to use the netket 3.0 code
- Fixed instances of nk.variation to use nk.vqs instead
- Fixed plotting of Symmetric RBM

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Welcome @pesvut,
and thanks a lot for updating and fixing the notebook!

**Review by PhilipVinc — APPROVED** [review]

**Comment by gcarleo** [comment]
just wondering why the new version is slower (it might be just a difference in CPU type though...)

**Comment by PhilipVinc** [comment]
I had run the previous one on my computer, which is quite beefy...

**Comment by pesvut** [comment]
Glad I could help :)

**Pull request merged**
