### PR TITLE
Update docstrings to conform sphinx rst 

### PR DESCRIPTION
**Pull request by gcarleo**
This PR addresses the issues and limitations related to maintaining a custom-based solution for documentation (see for example #216, as well as the complexity of the jekyll-based current website). 

We now switch to a sphinx-based system, where docstrings are still written (as before) in Google style. The only main difference is that math formulas are now to be written using sphinx's [math enviroment ](https://shimizukawa-sphinx.readthedocs.io/en/latest/ext/math.html). 

Docs for new classes however are very easy to add, using the sphinx facilities. The only requirement is to add entries to ```Docs/source/documentation.rst```. For example:

```rst
Operators
----------------

.. autosummary::
   :toctree: modules
   :nosignatures:

   netket.operator.BoseHubbard
   netket.operator.GraphOperator
   netket.operator.LocalOperator
   netket.operator.Ising
   netket.operator.Heisenberg
````

fully specifies documentations for operators. 

The web pages can be built going in ```Docs``` and doing ```make html``` (after having installed all the required sphinx extension). 

At present, there are some small inconsistencies in the web page rendering. Mostly in the main page (help is appreciated!!!).  This happens mostly because support of bootstrap in sphynx is not complete, and one needs to use raw html in most pages. 

**Notice that files in `source/modules/` are produced automatically by the autosummary extension and shouldn't be modified manually**

### CODE REVIEW

**Comment by femtobit** [comment]
This is great! I think the move to sphinx will make maintaining the documentation a lot easier.

Some things I noticed (at least when I render the pages on my machine):

Code blocks are not always rendered correctly, e.g. here, under "Examples" (and in many other places):
image

Formulas in `RbmSpinSymm` look broken:
image

Method arguments are not rendered correctly everywhere, e.g., in `hilbert.Spin`:
image

**Comment by gcarleo** [comment]
Thanks @femtobit , indeed there are still a few glitches. The main issue there is that the docstring format we were using now was taking $$ formula_here $$ for Latex, whereas sphinx accepts a [different syntax](https://shimizukawa-sphinx.readthedocs.io/en/latest/ext/math.html). This means that in principle we need to go through the docs one by one and change the formulas. I would like to avoid that, and I am still looking for an alternative

**Comment by gcarleo** [comment]
Ah maybe that's what we need! https://www.sympy.org/sphinx-math-dollar/

**Comment by gcarleo** [comment]
I have moved the Docs to the dedicated repository (netket-website), and it is now already online. We will still need to merge this branch for the changes done to some docstrings. 
The only thing I didn't do yet is to set up tests for the docs... It is less straightforward than I though with sphinx?

**Comment by femtobit** [comment]
Looks quite good now.

One more thing I noticed: On the pages of individual classes (for example [`Edgeless`](https://www.netket.org/modules/netket.graph.Edgeless.html#netket.graph.Edgeless)), there is no navigation in the sidebar. This would be pretty helpful to navigate back to the summary page, however.

**Comment by gcarleo** [comment]
> One more thing I noticed: On the pages of individual classes (for example Edgeless), there is no navigation in the sidebar. This would be pretty helpful to navigate back to the summary page, however.

Yes, that's something to improve, I also wanted to add that at some point. However at the moment I'd rather postpone this to another time also because to make it nice, it involves playing with templates/etc... 

I'd suggest we merge this now, so that future classes are documented with a consistent style!

**Pull request merged**
