### PR TITLE
move build configuration to pyproject.toml, remove setup.py

### PR DESCRIPTION
**Pull request by PhilipVinc**
In recent years there's been a push to deprecate declaring the build option of python packages with the overly complicated setup.py in favour of static build declaration in a `pyproject.toml` file together with one of many build tools (hatch, poetry...).

With the release of Python 3.11 next week, `setup.py` will be officially deprecated by setuptools as well (our current build system). 
The deprecation will probably last many years, but as we already require users to have a recent pip version (jax cannot be installed with pip older than 1 year or so), there's nothing bad with migrating to the new standard.

This PR is a draft at migrating our build configuration to pyproject. I'm going to keep it around so that I don't forget.

### CODE REVIEW

**Comment by ofek** [comment]
Hey! Have you considered Hatchling? (creator here)

It's now the default in the official [Python packaging tutorial](https://packaging.python.org/en/latest/tutorials/packaging-projects/).

**Comment by PhilipVinc** [comment]
Hi @ofek, I might be tempted to. But we use `setuptools_scm` for versioning from GitHub releases and it seems to me that this is not an equivalent plugin for hatch?

**Comment by ofek** [comment]
Yup! Example: https://github.com/psf/black/blob/f22273a72b3f1c15085f2d4a43e8d785bf48c822/pyproject.toml#L102-L109

**Comment by ofek** [comment]
Similar https://github.com/ionelmc/pytest-benchmark/issues/226

**Comment by ofek** [comment]
you can rerun, fixed https://github.com/pytest-dev/pytest-metadata/pull/55

**Comment by PhilipVinc** [comment]
I just realised that hatch makes the editable install work with intelligent code completion without extra pip arguments so this is clearly an improvement..

**Pull request merged**
