### PR TITLE
Add a test for paulistrings

### PR DESCRIPTION
**Pull request by gcarleo**

### CODE REVIEW

**Comment by gcarleo** [comment]
@PhilipVinc the test failing here "test_hermitian_local_operator_transpose_conjugation" is something I didn't expect (it's unrelated to this PR)

**Comment by PhilipVinc** [comment]
weird. This test never failed and is fairly straightforward. Let me try to rerun the tests...

**Comment by PhilipVinc** [comment]
it's weird. every time a different tester fails.

**Comment by PhilipVinc** [comment]
Now `test_copy` is failing.

**Comment by PhilipVinc** [comment]
I copied those tests in #539 , and found the reason for their odd failure.
I'll close this as it will get merged with #539

**Pull request closed without merging**
