### PR TITLE
Add PRNGSeq type and some tests

### PR DESCRIPTION
**Pull request by femtobit**
In order to make it a bit more convenient to derive `PRNGKey`s from one initial key, this PR adds a `PRNGSeq` type (inspired by Haiku's `PRNGSequence`, though it does not share the implementation -- I think this simpler implementation should be sufficient for our purposes).
```python
>>> hi = netket.hilbert.Spin(s=1/2, N=10)
>>> rseq = netket.jax.PRNGSeq(12)
>>> hi.random_state(next(rseq))
DeviceArray([ 1., -1., -1., -1., -1., -1.,  1., -1., -1., -1.], dtype=float32)
>>> nk.variational.MCState(..., seed=next(rseq))
```

(This is a PR on branch `nk3`, if it is merged into `master` soon it can of course be retargeted.)

This also bumps the required version of `mpi4jax>=0.2.10`, since the test of `mpi_split` added here was failing for me without it.

### CODE REVIEW

**Comment by femtobit** [comment]
The tests here should currently fail with the same error that occurs in #539, which also happens to me locally at the moment:
```
TypeError: Module construction attributes are frozen.
```
When this is fixed in `nk3`, I can rebase.

**Comment by PhilipVinc** [comment]
Thanks. I'll review in a few days, as I'm busy right now,

The error is because Google has slightly changed the behaviour of module setup in flax==0.3.1 which was released a few days ago. 
I don't agree with their choice so I opened [Flax#1057](https://github.com/google/flax/issues/1057) about it.
In the meantime I'll fix it in netket when I find the time.

**Comment by PhilipVinc** [comment]
You can also revert to flax==0.3.0 in the meantime

**Comment by PhilipVinc** [comment]
If you rebase tests should pass now

**Comment by PhilipVinc** [comment]
Seems good to me.

**Comment by PhilipVinc** [comment]
```python 
    def take(self, num = None: Optional[int]):
        """
        Returns an array of `num` PRNG keys and advances the iterator accordingly.
        """
        if num is None:
            _num = 1
        else:
            _num = num
        keys = jax.random.split(self._current, num=num + 1)

        self._current = keys[-1]

        if num is None:
            return keys[0]
        else:
            return keys[:-1]

```

can't we have something like this?

**Pull request merged**
