### PR TITLE
Add kwargs to Common Lattices

### PR DESCRIPTION
**Pull request by chrisrothUT**
Allows keyword arguments to be passed through common lattices.

### CODE REVIEW

**Comment by femtobit** [comment]
Good idea, thanks @chrisrothUT.

Could you add a docstring? The other methods have:
```
kwargs: Additional keyword arguments are passed on to the constructor of
            :ref:`netket.graph.Lattice`.
```

**Review by femtobit — APPROVED** [review]

**Review by PhilipVinc — CHANGES_REQUESTED** [review]
a test?

**Comment by chrisrothUT** [comment]
Added a test where I pass a kwarg to a lattice

**Comment by PhilipVinc** [comment]
thanks! last thing then it's good for me. Can you check by building locally that the link in the signature to `nk.graph.lattice` is correctly picked up by the documentation generator?

(to build the docs it's easy:
```
cd netket
pip install -r docs/requirements.txt
cd docs
make html
open _build/html/index.html
```

**Comment by chrisrothUT** [comment]
It appears when I build locally the block that says "inheritance" in `nk.graph.Lattice` does not display. 

It also appears that common lattices don't display in the documentation at all, which was the case before this PR.

**Comment by PhilipVinc** [comment]
inheritance is not shown for functions and I believe all those are just constructors?

Well, can you then add another table wit a list of the lattices we support?

**Review by PhilipVinc — APPROVED** [review]

**Comment by PhilipVinc** [comment]
Thanks for adding the test!

I'll merge since this is indeed useful.

If you have some time in the future, could you do a PR to address this comment ? 
>It also appears that common lattices don't display in the documentation at all, which was the case before this PR.

It's rather straightforward: you just need to list the lattices in this file https://github.com/netket/netket/blob/master/docs/docs/api.md

**Pull request merged**
