### PR TITLE
support pytrees as diag_shift

### PR DESCRIPTION
**Pull request by inailuig**

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Can you add a test?

**Comment by gcarleo** [comment]
what do you want to add to the diagonal?!!?

**Comment by PhilipVinc** [comment]
it's to do what Pauline should do.

**Comment by inailuig** [comment]
Test seems to pass.

In order to make it consistent with the rest ideally we would have to convert the diag_shift pytree (do real/imag split, ravel etc) in the constructor of QGTJacobianPyTree (when not holomorphic) and QGTJacobianDense, but I am not sure there is a need to do it now.

**Review by PhilipVinc — APPROVED** [review]

**Pull request merged**
