### PR TITLE
Rename 'MetropolisSampler.n_sweeps' to 'sweep_size' #1657

### PR DESCRIPTION
**Pull request by iamoeg**
This PR applies the following changes:

- Rename `MetropolisSampler.n_sweeps` to `sweep_size`
- Add deprecation warning when `n_sweeps` is used when constructing the sampler
- Update all code references to `n_sweeps` to use `sweep_size` instead
- Update documentation (docs, tutorials, and examples) to use `sweep_size`
- Adjust tests (sampler, variational, and models) to use `sweep_size`
- Update the Changelog to document the deprecation of `n_sweeps`

Use diff for file-level changes.

#### Test Results:

- Some tests failed or raised a warning, but most of them are relative to the `jax` package
- The other tests that failed or raised a warning are flagged as "flaky" in the test suite itself (e.g. `sampler.test_sampler.test_correct_sampling`)

See test results attached for details.

#### Attachments:

Text output files of test results for `sampler`, `variational`, `models`, as well as the full test suite:

- [test-results-full.txt](https://github.com/netket/netket/files/13662047/test-results-full.txt)
- [test-results-models.txt](https://github.com/netket/netket/files/13662049/test-results-models.txt)
- [test-results-sampler.txt](https://github.com/netket/netket/files/13662050/test-results-sampler.txt)
- [test-results-variational.txt](https://github.com/netket/netket/files/13662051/test-results-variational.txt)

#### Related Issues:

- #1657

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Hello @iamoeg . Thank you for chiming in! 

From a quick look, that is roughly correct.
 
However your PR contains a large number of unrelated changes coming from different formatting rules and some sort of import ordering plugin you're using. Import reordering, splatting of lines into multiple lines, huge changes to most lines in CHANGELOG...

I'm very sorry, but this makes reviewing the code much harder. In general when someone new comes along we have to be extra careful with the changes and check the code line by line. This adds a lot of noise and makes it harder.
 
I will review once all those irrelevant changes are removed.

(Note: in some cases, some of those might make sense. If it's just a few, that's ok. Otherwise that's another PR.)

**Comment by iamoeg** [comment]
Hello again!

I just reviewed the diff between my code and the project's master branch and it seems indeed that some of my tooling conflicts with yours: I use Flake8, Black and isort for Python development on VS Code, and I suspect Prettier to be responsible for the changes in CHANGELOG.

Anyway, I'll see if I can give it a go in a new workspace with none of the extensions installed and let the pre-commit hook take care of the linting, formatting, etc. But I suggest adding a little section about this in the developer documentation, or even provide a workspace config file for VS Code.

In all cases, thank you for your feedback @PhilipVinc; I guess we'll talk again when I resubmit. Have a good one in the meantime!

**Comment by PhilipVinc** [comment]
> Anyway, I'll see if I can give it a go in a new workspace with none of the extensions installed and let the pre-commit hook take care of the linting, formatting, etc. But I suggest adding a little section about this in the developer documentation, or even provide a workspace config file for VS Code.

Do open a PR for that. I have never touched this kind of thing and have no time to do it myself those days.

**Comment by iamoeg** [comment]
Hello again @PhilipVinc!

As discussed, I discarded my previous commit and made the necessary changes in a new environment. This should fix the issues that you raised earlier regarding formatting, and hopefully it's easier to review. See #1680 for details.

As for the changes made, what was stated originally is still relevant. So there are no changes on that front apart from the test results perhaps, but I'm including the details in the new PR as well for archiving and traceability.

Looking forward for your feedback!

**Pull request closed without merging**
