### PR TITLE
Shorthands for Pauli's LocalOperators

### PR DESCRIPTION
**Pull request by PhilipVinc**
This PR adds shorthands to construct Pauli and bosonic creation/destruction operators as LocalOperators.

It allows one to define a spin hamiltonian and jump operators with the following code:
```python
g = nk.graph.Hypercube(length=L, n_dim=1, pbc=True)
hi = nk.hilbert.Spin(s=0.5, graph=g)

ha = nk.operator.LocalOperator(hi)
j_ops = []
for i in range(L):
    ha += (gp / 2.0) * nk.operator.sigmax(hi, i)
    ha += (Vp / 4.0) * nk.operator.sigmaz(hi, i) * nk.operator.sigmaz(hi, (i + 1) % L)
    j_ops.append(nk.operator.sigmam(hi, i)

```

This works for arbitrary Spins and similarly for bosons, where `create/destroy/number` are implemented.

### CODE REVIEW

**Comment by gcarleo** [comment]
Thanks @PhilipVinc , I would have a slight preference for sigma_x sigma_y

**Comment by PhilipVinc** [comment]
I was trying to be consistent with QuTip and QuantumOptics.jl.

I don’t know other packages what do they use.

I’m not opinionated but I’d value consistency.


Il 12 mar 2020, 15:13 +0100, Giuseppe Carleo <notifications@github.com>, ha scritto:

**Comment by femtobit** [comment]
It's bikeshedding, of course, but for what it's worth, I also think consistency with QuTiP would be nice.

**Comment by gcarleo** [comment]
OK fine!

**Comment by gcarleo** [comment]
The only thing is that I believe that it would be nice to have a creation and destruction operator for bosons that is not making use of the cutoff in the occupation number (as much as the BoseHubbard hamiltonian is implemented right now)
Maybe we can do this in another PR

**Comment by femtobit** [comment]
To add a bit more to the bikeshedding, I do find the naming of `netket.operator.create` (what is it creating?) confusing enough that I might be willing to argue for deviating from QuTiP here. Something like `boson_creator` and `boson_annihilator` would be much clearer.

**Comment by PhilipVinc** [comment]
This starts to be a bit verbose for my taste, but okay.
Especially for sigma_x/y/z that are clearly spin operators.

**Comment by PhilipVinc** [comment]
@gcarleo I addressed your points. Now this exports 
```
from netket.operator.spin.sigmax/y/z/p/m
from netket.operator.boson.create/destroy/number
```

**Pull request merged**
