### PR TITLE
WIP: NetKet v3.0

### PR DESCRIPTION
**Pull request by gcarleo**
This is a WIP pull request for version 3.0 

Major goals for this release: 

- [x] Remove all C++ code 
- [ ] Improve documentation and tutorials 
- [x] Define and efficiently use models and samplers in JAX 
- [x] Define and use models in PyTorch 
- [x] GPU support

Breaking changes:

- ```netket.optimizer``` objects (including ```SR```) are now constructed passing also an explicit ```netket.machine.AbstractMachine``` object for example 

```python
machine=nk.machine.Rbm(alpha=1,hilbert=hi)
opt=nk.optimizer.Sgd(machine,learning_rate=0.01)
```

- ```log_val``` and ```der_log``` methods in machines derived from ```netket.machine.AbstractMachine``` now accept only batched inputs (matrices) 
- ```netket.utils.seed``` is now in ```netket.random.seed``` together with all other random methods

Main Remaining Tasks :

- [x] Rewrite ```graph.Lattice``` in python #405 
- [x] Make ```machine.Torch``` compatible with the latest Jacobian Vector function #363 
- [x] Add missing samplers in ```sampler.jax.*``` #416
- [x] Make dispatching over optimal sampling/optimizer backends automatic #413 
- [ ] Write tutorials on the use of backends and GPU #410 
- [x] MPS wave-functions in JAX #390

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@gcarleo I've been seeing a lot of those lately

```
/Users/filippovicentini/Documents/pythonenvs/netket_v21_env/lib/python3.7/site-packages/netket/sampler/metropolis_local.py:12: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
```

**Comment by gcarleo** [comment]
> /Users/filippovicentini/Documents/pythonenvs/netket_v21_env/lib/python3.7/site-packages/netket/sampler/metropolis_local.py:12: NumbaDeprecationWarning: The 'numba.jitclass' decorator has moved to 'numba.experimental.jitclass' to better reflect the experimental nature of the functionality. Please update your imports to accommodate this change and see http://numba.pydata.org/numba-doc/latest/reference/deprecation.html#change-of-jitclass-location for the time frame.
> ```

Yes, indeed it seems that they moved it to experimental... we should probably do the same when importing it. Actually I think that in general for the moment we should avoid using jitclass as much as possible

**Comment by PhilipVinc** [comment]
If I'm not mistaken we can now remove C++ stats, no?

**Comment by gcarleo** [comment]
> If I'm not mistaken we can now remove C++ stats, no?

Yes, hopefully also Utils can be already removed?

**Comment by PhilipVinc** [comment]
I'd like to merge #496 and then I think the time has come for this PR to be merged and move the development to main.
On the bright side: netket will show up as a (sigh) python package.

**Review by PhilipVinc — APPROVED** [review]

**Comment by PhilipVinc** [comment]
@gcarleo Do you want to push this 570 commit button?

**Comment by gcarleo** [comment]
Yes I think it's time to move this to master

**Pull request merged**
