### PR TITLE
Autoflush Json Logger

### PR DESCRIPTION
**Pull request by PhilipVinc**
I'm annoyed by the fact that if I run mildly long calculations, json logger flushes at his arbitrary interval of 50 steps. 
At the same time, for very long simulations flushing continuously might start taking a lot of time (or also for very fast, short simulations).

We need to teach Json Logger to behave better.

So, hereby I present a solution I've been using for a while: [AutoFlush](https://www.rainmanusa.com/wp-content/uploads/2019/11/Rainman-Autoflush.jpg), building on decades of experience of AI in the field of flushing everything, the JsonLogger would use a very advanced algorithm to decide whever to flush before the step_interval has passed:

 - a maximum Flushing runtime cost is specified as a fraction of total runtime FRAC (0.005 by default, which is .5 per cent)
 - Every flushing is monitored and timed
 - Every time we log data, if T_FLUSH / (TIME.NOW() - TIME_OF_LAST_FLUSH) > FRAC then we also flush.

Evidently, as I am aware of the adverse health effects of never flushing, we still flush when we would flush normally ( so every 50 steps, or when specified, or at the end of simulations).

We simply will be flushing reasonably more often to provide a better experience to customers while not wasting too many precious resources.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@femtobit if you think this makes sense, and if we decide on a better kwarg than 'runtime_cost', I'll add a bunch of extra tests.

**Comment by PhilipVinc** [comment]
(not an April's fool by the way)

**Comment by femtobit** [comment]
I think `autoflush_cost` is fine as name.

Personally, I'd start thinking about a more efficient output format then JSON if the serialization time becomes to noticeably large - but I can see that this can be useful if a quick solution is desired.

**Comment by PhilipVinc** [comment]
i was mainly wondering if keeping it as a fraction [0,1] or as a percent [0,100].

I had started investigating other formats that are decently supported, but found.. not much.
If you have proposals, I'm all ears.

Personally, I often use tensorboard those days. It's an over-engineered, opaque format, but it's easily extensible, and you can dump to it practically anything and de-serialize it to the right object. 
The only real complication is that... in python land there is no way to read back that data if not through tensor board.
I wrote a library to de-serialize it in Julia, which is why it kind of works for me, but that's far from ideal.

**Comment by gcarleo** [comment]
Looks like a good idea!

**Review by femtobit — APPROVED** [review]
> i was mainly wondering if keeping it as a fraction [0,1] or as a percent [0,100].

Personally I prefer fractions but that's mostly a matter of taste. If the numbers get to many zeros it's always possible to write `5e-4` or so.

In any case, the PR looks good to me.

**Comment by PhilipVinc** [comment]
Lets keep fractions.
I'll add a test and merge

**Pull request merged**
