### PR TITLE
Rename implementation files in netket.operator

### PR DESCRIPTION
**Pull request by femtobit**
As brought up in issue #445, it can be confusing (at least with auto-completion) if `netket.operator` contains both `LocalOperator` directly (which users are supposed to use) and the submodule `local_operator.py` where that class is implemented. Thus, this implementation file is renamed. And for consistency, so are all the others to which the same argument applies.

Since none of the current PRs modify any operator code, now seems to be as good as time as any to do this with minimal conflicts.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
This will wreck havoc when rebasing, so let's do it now and forget about it

**Comment by PhilipVinc** [comment]
Actually, before doing this, can we just check what is the customary way to do this in python packages?

It seems weird to me that all file names should start with underscores...

**Comment by femtobit** [comment]
@PhilipVinc I think this is relatively common, see e.g. [PyTorch](https://github.com/pytorch/pytorch/tree/master/torch) which has lots of underscore-prefixed files. Jax does it too a lesser degree, but see. e.g, [`_util.py` here](https://github.com/google/jax/tree/master/jax/numpy).

I think other packages often (a) put more code in a single file or (b) do not care too much about this "namespace cleanness". Since for the purpose of supporting `from package import *` you can define `__all__`, this is mostly just an issue with autocompletion.

**Comment by PhilipVinc** [comment]
Yes, you are right. I was just checking QuTip and indeed they don't care about this.
But we are perfectionists, so... let's merge ahead ⛵!

**Comment by gcarleo** [comment]
Cool go ahead! I won't be able to review this soon sorry

**Comment by femtobit** [comment]
There are some other places were we should also cleanup the file structure, but since there are some open PRs touching several of those, I think it's best if we wait until v3.0 is ready for release otherwise.

**Comment by PhilipVinc** [comment]
agreed

**Pull request merged**
