### PR TITLE
Run distributed tests on CI

### PR DESCRIPTION
**Pull request by inailuig**
jax 0.4.23 added cpu collectives with gloo, so now we can run the distributed tests on cpu.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@inailuig what's the speed of gloo wrt mpi?

**Review by PhilipVinc — APPROVED** [review]
Can you add a comment on the docs about using gloo as well in lieu of MPI?

**Comment by gcarleo** [comment]
It is quite interesting that, at least in 2020, MPI was a superior choice both for GPU and CPU... https://mlbench.github.io/2020/09/08/communication-backend-comparison/ I wonder if this is still true

**Comment by PhilipVinc** [comment]
I would expect the same results, unfortunately...

**Comment by inailuig** [comment]
> Can you add a comment on the docs about using gloo as well in lieu of MPI?

see https://netket--1679.org.readthedocs.build/en/1679/docs/sharp-bits.html

**Comment by inailuig** [comment]
> thanks. the run that fails is one of the usual mysterious errors. Can still be merged if you think it's unrelated.

It's the kind of killed CI run that magically got fixed by doing nothing and just running again last time. It's not OOM, don't quite know why it happens nor how to debug it, given it runs just fine by hand. Maybe we can try debug it again at a later date.

**Pull request merged**
