### PR TITLE
Fix the documentation of our flax modules / NNs to be finally readable

### PR DESCRIPTION
**Pull request by PhilipVinc**
Compare current website https://netket.readthedocs.io/en/latest/api/_generated/models/netket.models.RBM.html#netket.models.RBM 

with this PR
https://netket--1641.org.readthedocs.build/en/1641/api/_generated/models/netket.models.RBM.html#netket.models.RBM

Also 

master MLP
https://netket.readthedocs.io/en/latest/api/_generated/nn/netket.nn.blocks.MLP.html#netket.nn.blocks.MLP

this PR MLP
https://netket--1641.org.readthedocs.build/en/1641/api/_generated/nn/netket.nn.blocks.MLP.html#netket.nn.blocks.MLP

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Also solves all build errors of our documentation, so now we could theoretically make it error in CI if someone does not write docs correctly...

**Comment by PhilipVinc** [comment]
unless @gcarleo is against, I'm merging this asap because it's a big improvement...

**Comment by gcarleo** [comment]
I like it of course, but is there a way to get the methods/attributes of the models ? say, n_parameters etc

**Comment by PhilipVinc** [comment]
`MCState.n_parameters` ? or some methods in https://flax.readthedocs.io/en/latest/api_reference/flax.linen/module.html#flax.linen.Module 

Those are just the flax models. Before this PR the documentation is essentially unreadable between all the inherited members and stuff that is misrendered.

That's my best effort for now :) before taking a break from all those PRs for a bit.

**Comment by gcarleo** [comment]
ah yes sorry I meant MCState.n_parameters but that's not a problem, ok to merge! thanks

**Review by gcarleo — APPROVED** [review]

**Pull request merged**
