### PR TITLE
Last changes in branch 2.0 

### PR DESCRIPTION
**Pull request by gcarleo**

### CODE REVIEW

**Comment by gcarleo** [comment]
@jamesETsmith let's merge this, so that we can finally 'officially' release 2.0 in pip, and also add a link to the 2.0 version tag in the paper !

**Comment by femtobit** [comment]
Did we check whether the docs build correctly in `v2.0`? Everything else looks good to me as well.

**Comment by gcarleo** [comment]
@jamesETsmith OK, I have updated the binder link to the (future) tag release v2.0. The link does not work now, but it will work as soon as we promote master to tagged release v2.0. 

@femtobit the python help/docs should be OK (the pybind11 docstrings are generated when pip installing). There might be some markdown files that are not up to date, but that's fine, strictly speaking they are not part of the release, they are part of the website...

**Comment by jamesETsmith** [comment]
Great, thanks @gcarleo!

**Pull request merged**
