### PR TITLE
LocalOperator: Don't return the diagonal element if it is zero

### PR DESCRIPTION
**Pull request by PhilipVinc**
This PR does two things. The main thing of the PR is the following:

 - If the diagonal of a LocalOperator is zero, meaning that all the diagonal elements of all operators are 0 and the constant shift is zero, then we no longer return `x` with `mel=0` when calling `get_conn(x)`.

While this is negligible in the case of hamiltonians, as it's only 1 nonzero element, in the case of liouvillians we have terms like `\sum_i L_i\otimes L_i` where L usually has no diagonal elements, so in the best case scenario we were getting `4N` nonzero elements where actually only `N` are potentially nonzero.

This PR leads to a speedup of 20% so I think it's a good thing.
The points where we have to compute whever those elements are nonzero are several, and it's messy, but I hope to address this in the future by rewriting localoperator...

-- 
- The other thing that this PR does is giving a method to compute the maximum number of nonzero elements in an operator. This is useful for Liouvillians to preallocate the space needed before calling `get_conn`.  

todo: tests

### CODE REVIEW

**Comment by gcarleo** [comment]
I didn't realize this was causing a significant slowdown, good catch! and yes, we should have a method to just trim all zero elements even on the off diagonal... for example we have seen that for PauliString this is a problem

**Review by gcarleo — APPROVED** [review]

**Comment by PhilipVinc** [comment]
I think `LocalOperator.get_conn` will not return off-diagonal elements that are zero.
Only the diagonal element is returned if at least one is nonzero.
I was looking at whever we can avoid returning it all the time but It complicates further the code...

```python
>>> hi=nk.hilbert.Spin(0.5)
>>> op=nk.operator.spin.sigmam(hi, 0)
>>> op.get_conn(hi.all_states()[0])
(array([], shape=(0, 1), dtype=float64), array([], dtype=float64))
>>> op.get_conn(hi.all_states()[1])
(array([[-1.]]), array([1.]))
```

**Comment by gcarleo** [comment]
the issue is that for off-diagonal elements there might be some duplicate entries (not sure) that have different (non zero) matrix elements summing to 0... so in principle we should put together the duplicate x' and sum up the mels associated with the duplicates

**Comment by PhilipVinc** [comment]
ah you mean that? yeah.
Another (cheaper) approach would be to 'compress' a LocalOperator in such a way that if you have like an Ising hamiltonian

```python
>>> nk.operator.Ising(hi, nk.graph.Chain(5), h=1).to_local_operator().acting_on
[[0], [1], [2], [3], [4], [0, 1], [0, 4], [1, 2], [2, 3], [3, 4]]
```

Instead of keeping all the local 1 body terms separated, we can just multiply them by the identity and sum them into the 2-body terms.
(In the case of Ising nothing changes, but in other cases this should reduce (not solve) the issue you mentioned)

**Pull request merged**
