### PR TITLE
Standardize use of AbstractGraph.n_nodes and add n_edges

### PR DESCRIPTION
**Pull request by femtobit**
Addressing one of the issues raised by @PhilipVinc in #514 with my suggestion of standardizing on `n_nodes` (also adding `n_edges` in the process).

Slight benefits compared to `n_vertices`:
1. `n_nodes` and `n_edges` have the same length.
2. networkx also uses the term nodes.

Slight downsides:
1. `n_nodes` is used a lot in the code to refer to MPI processes. This is unlikely to cause much confusion, though.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Could you also add an integrator on the `nodes`, much like edges? It might also have a default fallback definition of returning `range(self.n_nodes)`if you want.

**Comment by PhilipVinc** [comment]
I'd argue that we can put this in and then slowly convert the rest of netket.

**Comment by femtobit** [comment]
@PhilipVinc Should `nodes()` it be an iterator? I think so, but note that `edges()` is documented to return a `list`, explicitly. Maybe we should change that as well - not sure if this may have unintended consequences (i.e., breaking code somewhere) though.

**Comment by PhilipVinc** [comment]
To avoid breakage we can keep them both as lists.
In any case, for the use case of netket graphs are fairly small objects so we don't really need the lazy-ness of an iterator.

**Comment by femtobit** [comment]
After looking at it, having `.edges()` return an iterator affects only very little code fFor example, `np.asarray(g.edges())` needs to be changed, but that only occurred once), so this PR now does that and adds a `.nodes()` iterator. I think that makes the most sense as interface.

**Review by PhilipVinc — APPROVED** [review]

**Pull request merged**
