### PR TITLE
Fix incorrect shape in vmc._grads allocation

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by PhilipVinc** [comment]
I have no idea why this does not error when you then do 
```python
            self._grads = _np.conjugate(_der_logs) * eloc.reshape(-1, 1)
```
instead, it reallocates.

**Comment by femtobit** [comment]
@PhilipVinc That line will first create a new array for the right-hand side of the assignment and then assign this to the name `self._grads`. The old array that was referred to by `self._grads` previously will then be deallocated unless referenced elsewhere.

`self._grads[:] = ...` would assign to the existing `_grads` array and raise `ValueError` if the shapes do not match. (Though note that this will still create a temporary right-hand side, copy its contents into `_grads` and then that right-hand side will be deallocated. So assigning to `_grads` in this way would not actually save allocations, as far as I know.)

**Comment by gcarleo** [comment]
IS it worth merging this ?

**Comment by femtobit** [comment]
If the `self._grads = ` line is left as it is now, I'd rather remove the initialization of `self._grads` in `__init__`, as it only allocates memory that is never used.

And in case `_grads` would be read somewhere prematurely at some point, having empty memory seems like it could lead to harder to find bugs; maybe we should just set `self._grads = None` initially.

**Comment by gcarleo** [comment]
Yes indeed, I am now working on an another PR to start addressing #392 , and indeed we can just initialize many thing to None, without even assuming they are going to be numpy types
I am closing this for now!

**Pull request closed without merging**
