### PR TITLE
fix #768

### LINKED ISSUE #768: nk.nn.logcosh() always returns 0 when the argument is a purely imaginary number
There's a little bug in nk.nn.logcosh(): when its argument is a purely imaginary number, it would always return 0.
```python
import netket as nk
import jax.numpy as jnp

print(nk.nn.logcosh(0.1j))
print(jnp.log(jnp.cosh(0.1j)))
```
```
0j
(-0.005008355623235254+0j)
```

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by femtobit** [comment]
Would it make sense to add a test for `logcosh`?

**Comment by PhilipVinc** [comment]
Yeah, it would be a good idea.

**Comment by gcarleo** [comment]
I guess we can merge this?

**Review by gcarleo — APPROVED** [review]

**Comment by PhilipVinc** [comment]
@femtobit Now that I notice, to be consistent with ja/flax naming it should be `log_cosh` instead of `logcosh`.
Should we rename and deprecate?

**Comment by femtobit** [comment]
@PhilipVinc Sounds resonable.

**Review by femtobit — APPROVED** [review]

**Pull request merged**
