### PR TITLE
Move metropolis pt to stable

### PR DESCRIPTION
**Pull request by PhilipVinc**
Moves `MetropolisPt` to stable netket.

Just one thing: do we like `MetropolisPt` as a name? It's a bit short, though `MetropolisParallelTempering` is too long...

(cc @lindamauron what do you think?)

### CODE REVIEW

**Comment by lindamauron** [comment]
I personally prefer `MetropolisPT`, the other one is indeed a bit too long. 

If we don't need the `Metropolis` explicitly in the name, another solution would be to only have `ParallelTempering`. As the very concept is based on Metropolis, I doesn't seem ambiguous to me. But it would "break" the way we have named the samplers up to now, always containing `Metropolis`.

**Comment by PhilipVinc** [comment]
I agree with the fact that is should be called `MetropolisPT` and not `MetropolisPt` . 

Regarding just `ParallelTempering` ... I dunno. I'm not against. Can we get more opinions on that?

**Comment by PhilipVinc** [comment]
@gcarleo what about `ParallelTempering` without the Metropolis?

**Comment by gcarleo** [comment]
yes this is a good idea

**Comment by PhilipVinc** [comment]
So we agree (@gcarleo @lindamauron ) to have
`nk.sampler.ParallelTemperingSampler` the base sampler (to which you pass the transition rule)

And the prebuilt samplers with rules are
```
nk.sampler.ParallelTemperingLocal
nk.sampler.ParallelTemperingExchange
nk.sampler.ParallelTemperingHamiltonian
```

**Comment by PhilipVinc** [comment]
@gcarleo you like it?

**Comment by gcarleo** [comment]
looks good yeah

**Pull request merged**
