### PR TITLE
Adding a test for pauli string order

### PR DESCRIPTION
**Pull request by jwnys**
A test for issue #836  (@PhilipVinc ): check whether number of connected elements is independent of the order of X and Y, and whether output is correct.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Great! Thanks!
Can you just add a comment referencing your previous PR?

This will make it easy to trace it back in the future.

**Comment by jwnys** [comment]
Assuming you mean a comment here?
This is related to issue  #836

**Comment by PhilipVinc** [comment]
No I mean just above the test definition

**Comment by PhilipVinc** [comment]
I can do it in a few days too, when I have again access to a computer

**Comment by PhilipVinc** [comment]
Anyhow, thanks for this

**Comment by jwnys** [comment]
My bad, misunderstood, I added the comment

**Review by PhilipVinc — APPROVED** [review]

**Pull request merged**
