### PR TITLE
Fix numba issue

### PR DESCRIPTION
**Pull request by gcarleo**
this should fix a weird issue emerged in the last release of numba

### CODE REVIEW

**Comment by PhilipVinc** [comment]
If this fixes it, you should bump the minimum version of numba, unless this change is backward compatible

**Comment by gcarleo** [comment]
no the fix is backward compatible...

**Comment by PhilipVinc** [comment]
black black black

**Review by PhilipVinc — APPROVED** [review]

**Comment by gcarleo** [comment]
Looks like black is quite buggy, at this point I would be in favor of removing it from the compulsory checks and move it as a separate optional check (as suggested by @PhilipVinc )

**Pull request merged**
