### PR TITLE
[WIP] Add support for flax

### PR DESCRIPTION
**Pull request by PhilipVinc**

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Flax has finally fixed their issues with complex numbers! So this PR can be finished.

Flax has also recently released their new stable 'linen' API, to write networks, supporting non-trainable parameters out of the box. See [here](https://docs.google.com/document/d/1hYavTVPaKVVe9Be8pCB7yW7r6dDv3RALVNit8NZca4c) for the explanation or [here](https://github.com/google/flax/blob/f23cb3823fe27e60ecf3be4fc345e2f8593fde18/linen_examples/mnist/train.py#L35) for a CNN example.

Essentially, you can write networks like:
```python
class CNN(Flax.nn.Module):
  """A simple CNN model."""

  @nn.compact
  def __call__(self, x):
    x = nn.Conv(features=32, kernel_size=(3, 3))(x)
    x = nn.relu(x)
    x = nn.avg_pool(x, window_shape=(2, 2), strides=(2, 2))
    x = nn.Conv(features=64, kernel_size=(3, 3))(x)
    x = nn.relu(x)
    x = nn.avg_pool(x, window_shape=(2, 2), strides=(2, 2))
    x = x.reshape((x.shape[0], -1))  # flatten
    x = nn.Dense(features=256)(x)
    x = nn.relu(x)
    x = nn.Dense(features=10)(x)
    x = nn.log_softmax(x)
    return x
```

which is damn nice.
Then, to construct it you can do
```python
def get_initial_params(key):
  dummy_input = jnp.ones((1, 28, 28, 1), jnp.float32)
  initial_params = CNN().init(key, dummy_input)
  return initial_params
```

Notice that `CNN` is a subclass of the abstract class `flax.nn.Module`. I was thinking I could define a `netketModule` abstract class subclassing `flax.nn.Module` doing what our machine does, so that one won't need anymore to wrap a machine into Netket's machine class...

**Comment by gcarleo** [comment]
Very nice indeed! Sorry silly question but how do you define there the type of the parameters? Say I wanted complex parameters. 

And yes, it would be much more elegant if we could remove the machine.Jax class somehow and subclass directly the flax module

**Comment by gcarleo** [comment]
I guess we can close this now right?

**Comment by PhilipVinc** [comment]
yes, indeed. Implemented with #539

**Pull request closed without merging**
