### PR TITLE
Correct + operator in LocalOperator

### PR DESCRIPTION
**Pull request by gcarleo**
Hi @jamesETsmith , here is a possible solution to the issue you found out in #117 , please let me know if it works now (I added a test following your code and it does not seg fault)

### CODE REVIEW

**Comment by jamesETsmith** [comment]
When I move the code in `test_local_operator_ops()` outside of the function (I put it with the rest of the set up code that adds operators to the `operators` dictionary), I get a seg fault when `get_conn()` is called on the custom hamiltonian operator.

My modified version of your `test_operator.py` is below:

```python
import netket as nk
import networkx as nx
import numpy as np
from mpi4py import MPI

operators = {}

# Ising 1D                                                                                                                                                                                                
g = nk.graph.Hypercube(length=20, ndim=1, pbc=True)
hi = nk.hilbert.Spin(s=0.5, graph=g)
operators["Ising 1D"] = nk.operator.Ising(h=1.321, hilbert=hi)

# Heisenberg 1D                                                                                                                                                                                           
g = nk.graph.Hypercube(length=20, ndim=1, pbc=True)
hi = nk.hilbert.Spin(s=0.5, total_sz=0, graph=g)
operators["Heisenberg 1D"] = nk.operator.Heisenberg(hilbert=hi)

# Bose Hubbard                                                                                                                                                                                            
g = nk.graph.Hypercube(length=3, ndim=2, pbc=True)
hi = nk.hilbert.Boson(n_max=3, n_bosons=6, graph=g)
operators["Bose Hubbard"] = nk.operator.BoseHubbard(U=4.0, hilbert=hi)

# Graph Hamiltonian                                                                                                                                                                                       
# TODO (jamesETsmith)                                                                                                                                                                                     

# Custom Hamiltonian                                                                                                                                                                                      
# TODO (jamesETsmith)                                                                                                                                                                                     
#sx = [[0,1],[1,0]]                                                                                                                                                                                       
#szsz = [[1,0,0,0],[0,-1,0,0],[0,0,-1,0],[0,0,0,1]]                                                                                                                                                       
#sy = np.array([[0,1j],[-1j,0]])                                                                                                                                                                          
#                                                                                                                                                                                                         
# operators["Custom"] =                                                                                                                                                                                   
sx = [[0, 1], [1, 0]]
sy = np.array([[0, 1j], [-1j, 0]]).tolist()
sz = [[1, 0], [0, -1]]
g = nk.graph.CustomGraph(edges=[[i, i + 1] for i in range(20)])
hi = nk.hilbert.CustomHilbert(local_states=[1, -1], graph=g)

sx_hat = nk.operator.LocalOperator(hi, [sx] * 3, [[0], [1], [5]])
sy_hat = nk.operator.LocalOperator(hi, [sy] * 4, [[2], [3], [4], [9]])
szsz_hat = nk.operator.LocalOperator(hi, sz, [0]) * nk.operator.LocalOperator(
    hi, sz, [1])
szsz_hat += nk.operator.LocalOperator(hi, sz, [4]) * nk.operator.LocalOperator(
    hi, sz, [5])
szsz_hat += nk.operator.LocalOperator(hi, sz, [6]) * nk.operator.LocalOperator(
    hi, sz, [8])
szsz_hat += nk.operator.LocalOperator(hi, sz, [7]) * nk.operator.LocalOperator(
    hi, sz, [0])

operators["Custom Hamiltonian"] = sx_hat + sy_hat

rg = nk.utils.RandomEngine(seed=1234)

def test_produce_elements_in_hilbert():
    for name, ha in operators.items():
        hi = ha.get_hilbert()
        print(name, hi)
        assert (len(hi.local_states()) == hi.local_size())

        rstate = np.zeros(hi.size())

        local_states = hi.local_states()

        for i in range(1000):
            hi.random_vals(rstate, rg)
            print("BEFORE")
            conns = ha.get_conn(rstate)
            print("AFTER")

            for connector, newconf in zip(conns[1], conns[2]):
                rstatet = np.array(rstate)
                hi.update_conf(rstatet, connector, newconf)

		for rs in rstatet:
                    assert (rs in local_states)
```

**Comment by gcarleo** [comment]
Hi @jamesETsmith , please try this one... it should be OK !

**Comment by gcarleo** [comment]
Yeah the problem was (I think) that the `+=` operator (and the others) were returning a reference to `*this`. However since `Operator` is handled as a shared pointer, most likely those references were trashed right after they were assigned, causing some seg fault... I mean, the ugly solution that works here is to return things by value and not by reference. There might be the possibility to improve on performance returning shared pointers though... Are these changes good for you to finish the other PR/ reshape your `GraphOperator`? Let me know if I need to do more stuff on this! Thanks

**Comment by jamesETsmith** [comment]
I think it should, thanks for your help!

**Pull request merged**
