### PR TITLE
Do not use `FrozenDict` in `MCState` anymore

### PR DESCRIPTION
**Pull request by PhilipVinc**
Flax deprecated frozendicts, so we may do as well.

If we just stop returning frozenDicts, an user might be able to change parameters implicitly by editing the parameters

```python
vs = MCState(...)
pars = vs.parameters
pars['Dense']['Kernel'] = my_array

# now we have that
assert vs.parameters['Dense']['Kernel'] == my_array
# True
```

so to avoid doing that, we can just make sure that `vs.parameters` always returns a copy of the underlying parameters (note that it's just a copy of the dictionary, not a copy of the parameters themselves which are immutable). 
This comes at a small cost, but should prevent bugs from arising in user code, and for large enough models this should be negligible.

The slowdown for an RBM is of the order of 1000
```python
In [1]: %timeit vs.parameters
2.1 µs ± 13.5 ns per loop (mean ± std. dev. of 7 runs, 100,000 loops each)

In [2]: %timeit vs._parameters
7.56 ns ± 0.0178 ns per loop (mean ± std. dev. of 7 runs, 100,000,000 loops each)
```
but I think this is largely irrelevant unless someone is accessing parameters thousands of time per second without using them.

### CODE REVIEW

**Comment by gcarleo** [comment]
Do we go from freezing and unfreezing to popping and unpopping? 😂

**Comment by PhilipVinc** [comment]
no, popping is internal. to split differentiable parameters from non differentiable ones.

**Comment by PhilipVinc** [comment]
(we were already popping before)

**Comment by PhilipVinc** [comment]
In the current state we return a copy. This is safe to ship as is as it is a strict improvement over the past.

Whether to return a copy or not, we can discuss and I'm open to feedback.

Mainly, unless there is a problem with the performance hit I think it's safer to return a copy.

**Comment by gcarleo** [comment]
Is there an alternative to returning a copy? say, can we return a view instead or similar?

**Comment by PhilipVinc** [comment]
It's a copy of the dictionary, but not of the data inside of it. 
Jax arrays (and therefore our parameters) are immutable so there is no concept of view in jax.
A shallow copy if you want.

The issue I'm raising is because if one has a very complicated parameter structure with lots of different arrays in the dictionary of parameters, the time it takes to generate a dictionary that points to the same arrays ( a shallow copy) might eventually be large, because python is slow.

Though python has been getting a bit faster recently and for large networks I'd expect large runtime in evaluating the network anyway so I'm unsure if this fear is justified.

**Comment by gcarleo** [comment]
Indeed

**Comment by wdphy16** [comment]
Sorry I just realized that even a commit message will spam here...

**Pull request merged**
