### PR TITLE
GCNN Bug Fixes

### LINKED ISSUE #1405: Passing masks to a GCNN has no effect
Hi, first of all I'm sorry if this actually belongs in the discussions section, I've never worked with github before and don't know what problems are Issues-worthy.

I noticed that after the new implementation of the masked GCNNs, passing masks to the GCNN does not have any effect, e.g. for a model with only 2nd nearest neighbors convolutions the number of parameters does not change, so
```
# Define system
L = 8
lattice = nk.graph.Square(length=L)
hi = nk.hilbert.Spin(s=1 / 2, total_sz=0, N=lattice.n_nodes)

# Define Metropolis-Hastings sampler
sampler = nk.sampler.MetropolisExchange(hilbert=hi, graph=lattice)

# Define the model: masked GCNN
input_mask = np.zeros([L, L])
for i in range(-1, 2):
    for j in range(-1, 2):
        input_mask[i][j] = 1
input_mask = input_mask.ravel()
hidden_mask = np.repeat(np.expand_dims(input_mask, 1), repeats=8, axis=1).ravel()

machine = nk.models.GCNN(symmetries=lattice, layers=2, features=(4, 2), param_dtype=jnp.complex128,
                         input_mask=input_mask, hidden_mask=hidden_mask)
vstate = nk.vqs.MCState(sampler=sampler, model=machine)
print("number of parameters:", vstate.n_parameters)
```
returns `number of parameters: 4358` instead of the desired `number of parameters: 618`

I think the error is that in `netket.models.equivariant` , the masks are not passed on from the general GCNN method  to the constructors of the different modes (FFT, irreps).

Also, if I use the DenseSymm layer with a mask I get an error, so changing the model in the above code to 
`machine = nk.nn.DenseSymm(symmetries=lattice, mode="matrix", mask=HashableArray(input_mask), features=2)
` 
gives the error `TypeError: nonzero requires ndarray or scalar arguments, got <class 'netket.utils.array.HashableArray'> at position 0.`

It should work if `self.kernel_indices = jnp.nonzero(self.mask)[0]`  in the `DenseSymmMatrix` class
is changed to `(self.kernel_indices,) = np.nonzero(self.mask)`, as in the other modes.

### PR DESCRIPTION
**Pull request by chrisrothUT**
This PR fixes the bugs described in https://github.com/netket/netket/issues/1405. 

Fix #1405

### CODE REVIEW

**Review by PhilipVinc — APPROVED** [review]

**Comment by PhilipVinc** [comment]
Very nice, thank you Chris.Can I ask you to add two tests, just to be safe? For example that if you pass a mask the number of parameters goes down and maybe that you can pass an array as a mask…On 8 Feb 2023, at 23:15, codecov[bot] ***@***.***> wrote:﻿
Codecov Report

Merging #1428 (2b5ebca) into master (59f9e66) will decrease coverage by 0.02%.
The diff coverage is 83.33%.

@@            Coverage Diff             @@
##           master    #1428      +/-   ##
==========================================
- Coverage   82.20%   82.19%   -0.02%     
==========================================
  Files         229      229              
  Lines       12762    12766       +4     
  Branches     1958     1960       +2     
==========================================
+ Hits        10491    10493       +2     
- Misses       1752     1753       +1     
- Partials      519      520       +1     



Impacted Files
Coverage Δ





netket/models/equivariant.py
86.47% <ø> (ø)



netket/nn/symmetric_linear.py
83.06% <83.33%> (-0.43%)
⬇️



Help us with your feedback. Take ten seconds to tell us how you rate us. Have a feature suggestion? Share it here.

**Comment by PhilipVinc** [comment]
Ok, I added the tests for DenseSymm (and found out there were a few bugs, and fixed em), can you add the ones for GCNN to be sure there are no bugs?

**Comment by PhilipVinc** [comment]
@chrisrothUT I would like to tag a new release of netket and the last thing that is missing is this bug fix... Can I ask you to add a test that would have failed before this fix for the GCNN (so checking that the masks are specified?)

**Comment by chrisrothUT** [comment]
Okay I added a test to make sure the masks are being used correctly

**Comment by PhilipVinc** [comment]
Lovely! Thanks a lot! When tests pass on CI I'll merge.

Early next week I'll tag a new release of netket...

**Comment by PhilipVinc** [comment]
Thank you!

**Pull request merged**
