### PR TITLE
Improve pytest project files

### PR DESCRIPTION
**Pull request by PhilipVinc**
This pr adds pytest-xdist to the dev dependencies together with coverage, uses the dev variant in travis and github CI to simplify the scripts, and adds a default setting for running pytest with no options in netket, making it's usage simpler when developing...

### CODE REVIEW

**Comment by gcarleo** [comment]
this looks OK to me, but maybe @femtobit has more thoughts?

**Comment by gcarleo** [comment]
some formatting issue it seems

**Comment by PhilipVinc** [comment]
From the rebasing, yes.
But it seems Travis is not liking this, for unknown reasons...

**Comment by femtobit** [comment]
> this looks OK to me, but maybe @femtobit has more thoughts?

Looks good to me as well, aside from the weird Travis issue here which I can't reproduce locally.

The linux builds in Travis seem to fail with some message related to `pytest-xdist`. Do the tests run without it?

**Comment by PhilipVinc** [comment]
@femtobit I addressed the Travis failure without disabling parallel tests.
@gcarleo This can be merged now

**Comment by PhilipVinc** [comment]
(But squash and merge. It's many useless commits)

**Comment by femtobit** [comment]
@PhilipVinc Cool! What was it that caused Travis to fail here? (The log overflow on Mac I understand, just not the error on Linux.)

**Comment by PhilipVinc** [comment]
So, I was triggering at different commits 2 different INTERNALERRORS (if you read carefully)
- one is trivial to fix, and it is due to an undocumented incompatibility between coverage.py >= 5 and pytest-xdist < 2.10.1 which has only very recently been fixed.
- the other one happens if you run coverage with mpirun, but without disabling distributed testing (xdist) through -n0. Even if you have only one process (-n1) you will trigger the internalerror. This i don't really understand but I had found an issue detailing this very same failure..

**Review by femtobit — APPROVED** [review]
I see, thanks for the explanation - the mpirun/xdist bug sounds pretty subtle indeed. But anyways, as long as `-n0` works that's good enough for me. :slightly_smiling_face:

**Pull request merged**
