### PR TITLE
Remove `is_holomorphic` and replace with `has_complex_weights` (+ R->C bug fix)

### PR DESCRIPTION
**Pull request by PhilipVinc**
After having harassed @gcarleo several times about our usage of `is_holomorphic`, I finally did a PR to fix (in my opinion) it.

In essence: 
 - In netket our usage of `is_holomorphic` was to check if the function had real parameters, to dispatch to a more efficient SR version.
 - While R->R functions are not holomorphic, R->C functions are holomorphic, even if the Cauchy conditions have to be reformulated (my favourite read is [this](http://dsp.ucsd.edu/~kreutz/PEI-05%20Support%20Files/Lecture%20Supplement%203%20on%20the%20Complex%20Derivative%20v1.3c%20F05%20.pdf)). 
 - If we have a C->C function that is not holomorphic netket breaks down anyways so...

I propose to change `is_holomorphic` to `has_complex_weights`. Now all machines specify their `dtype` (either float or complex) at construction.
Machines also  specify their output type, `outdtype`. this defaults to the same as the `dtype`, so if you don't specify it everything will stil work.

The main advantage in knowing the input and output type is that now we can correctly treat R->C wavefunctions during optimisation, and restrict the update to only the real part of the gradient. Previously this would fail (and was untested).

This is also used to speed up some jax gradients and vjp (from a previous PR).

This pr also:
 - Introduces a new Jax Pure machine that is R->C, and tests that der_log and vjp works 
 - I also add a bunch of density matrix machines
 - I fixed a bug with der log of jax R->C wavefunction that I missed in my last pr.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
tests won't pass because all the density matrix stuff has issues I'm still trying to solve

**Comment by PhilipVinc** [comment]
Tests are passing apart from some unrelated errors for `der_log_val`, which I'm still investigating...

**Comment by gcarleo** [comment]
I completely agree with the idea, and having two types for parameters and outputs makes things a lot more transparent.  

I am just unsure about whether we need ```has_complex_weights``` though, in the sense that it is just 

```python
    def has_complex_weights(self):
        return self._dtype is complex
```

so maybe we just need to make dtype (and outdtype) a public attribute and check those when needed? 

If we keep this convenience function, I would then suggest to call it ```has_complex_parameters```

**Comment by PhilipVinc** [comment]
Indeed dtype and outdtype are already exposed as public read-only properties.

My idea was to have a simple function to check this, without having to know what type (float) is in dtype. In case we ever want to change that part of the interface.

I agree with changing the name, however.

**Pull request merged**
