### PR TITLE
Conda builds on Mac 

### PR DESCRIPTION
**Pull request by gcarleo**
Solves old issue with conda builds on Mac see also #248 
Many thanks to lijun99 for the insight

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Hmm.
Ok it is weird. I did
```bash
➜ conda create --name conda-ket-test python=3.8
➜ conda activate conda-ket-test
➜ git clone git@github.com:netket/netket.git netket &&  git checkout conda_test
➜ cd netket && pip install .
➜ python -c 'import netket'
Traceback (most recent call last):
  File "<string>", line 1, in <module>
  File "/Users/filippovicentini/Desktop/condaket/nk/netket/__init__.py", line 18, in <module>
    from . import (
  File "/Users/filippovicentini/Desktop/condaket/nk/netket/dynamics.py", line 1, in <module>
    from ._C_netket.dynamics import *
ModuleNotFoundError: No module named 'netket._C_netket'
```

I'll have a more through look at this tomorrow

**Comment by gcarleo** [comment]
can you use the environment.yml file I put in this PR? I think that python 3.8 has some other issues...

**Comment by PhilipVinc** [comment]
It just works™!

**Comment by PhilipVinc** [comment]
```bash
git clone git@github.com:netket/netket.git netket &&  cd netket && git checkout conda_test
conda env create -f environment.yaml
😴 
pip install . 
😴 
cd ..
python netket/Examples/Ising1d/ising1d.py
mpirun -np 6 python nk/Examples/Ising1d/ising1d.py
```

produces the correct output

**Comment by gcarleo** [comment]
I think that it should work now, I had forgot to include mpi4py to the environment before

**Comment by PhilipVinc** [comment]
I still get build errors
https://gist.github.com/PhilipVinc/1785ab82744e1e836abe90e0e6687cd7

but it has nothing to do with Netket, it's probably the conda version of clang/llvm that is interfering somehow...

**Comment by gcarleo** [comment]
I think it's because of the Json include path that is somehow redundant and
causes issues with some versions of clang... I had fixed it already in the
PR on quantum state reconstruction but forgot to do it here as well... I
will take a look next week

**Comment by PhilipVinc** [comment]
It's a `conda-darwin-llvm` problem.

I _solved_ it by removing the three lines
```
  - clangxx_osx-64
  - clang_osx-64
  - gfortran_osx-64
```

from the environment file. Without them, CMake uses the system's compiler, netket compiles fine and there are no MPI problems. Running the ising1D example works with no issues

**Comment by gcarleo** [comment]
I think we are ready to merge this

**Comment by PhilipVinc** [comment]
I just tested locally and it works. merge ahead

**Comment by PhilipVinc** [comment]
By the way, I have been using for a while this Conda-build recipe and it works quite well.
When we release v2.1 we should release a condo recipe based on this, too...

the only issue with this one is that it disables MKL because I could not manage to get it to work, but should not be too hard...

```
[vicentinif@master0 netket]$ cat meta.yaml
{% set name = "netket" %}
{% set version = "2.1" %}

package:
  name: "{{ name|lower }}"
  version: "{{ version }}"

source:
  #url: https://github.com/netket/netket/tree/v2.1
  #sha256: ea1506f0350a231f623e3e01cc76daaede98d0ce4d2663270975f04169b37665
  git_url: https://github.com/netket/netket.git
  git_tag: v2.1

build:
  number: 0
  script: "{{ PYTHON }} -m pip install . --no-deps --ignore-installed -vvv --install-option=--cmake-args='-DNETKET_USE_LAPACK=OFF'"

requirements:
  host:
    - pip
    - python =3.7
    - blas
    - libopenblas
    - mpich
    - openmp
    - nomkl
  build:
    - {{ compiler('cxx') }}
    - {{ compiler('c') }}
    - cmake >=3.12
    - ninja
  run:
    - numpy >=1.16
    - python =3.7
    - scipy >=1.2.1
    - blas
    - libopenblas
    - matplotlib
    - mpich
    - mpi4py
    - openmp
    - nomkl

test:
  imports:
    - netket

about:
  home: http://github.com/netket/netket
  license: Apache 2.0
  license_family: APACHE
  license_file: LICENSE
  summary: Summary of the package
  doc_url: https://www.netket.org/documentation.html
  dev_url: https://github.com/netket/netket

extra:
  recipe-maintainers:
    - Ghosts
```

**Pull request merged**
