### PR TITLE
Switch from flax.optim to optax

### PR DESCRIPTION
**Pull request by PhilipVinc**
This also supports haiku out of the box. See the included example @femtobit

### CODE REVIEW

**Comment by PhilipVinc** [comment]
For info on development of optax: https://github.com/google/flax/discussions/1095#discussioncomment-450906
 --
@gcarleo Does not like the fact that optax uses lower-case names for optimisers like `optax.sgd, optax.adam`, ecc...

The reason they are lower-case is that they are functions building a _composite_ object that is the optimisers, 
```python
>>> import optax
>>> optax.sgd(0.1)
GradientTransformation(init=<function chain.<locals>.init_fn at 0x13421a5e0>, update=<function chain.<locals>.update_fn at 0x13421a670>)
```
and they are not really a class in itself.

Also, he says this is inconsistent with the fact that mostly everything else in netket is a class.
Also, our old optimisers where `nk.optimiser.Sgd(), nk.optimiser.Adam()`, ecc... so why change the API at all?

--
About the change I'd say that we are changing the API anyway: previously we required the machine to be passed in to our optimisers, but not anymore. 

Personally, I would prefer to get rid of optimisers from netket altogether and tell users to use optax directly (of course, well documenting this behaviour and giving examples). 
As I know I am in a minority regarding this, I'd push for what is in this pr: re-exporting a few optimisers from optax, and then telling our users that it's actually better to use optax directly.

As a transition, we could define `nk.optimiser.Sgd = optax.sgd` and so on with deprecation.

**Comment by femtobit** [comment]
For what it's worth, I agree with you regarding the optimizer names, @PhilipVinc, especially given that if we re-export `optax` functions anyways, renaming them ist just confusing. I'm 

Not that we are completely consistent with that anyways, `nk.optim.SR` is a function, for instance - and I definitely wouldn't want to rename it to `sr`.

**Comment by PhilipVinc** [comment]
@gcarleo ?

**Comment by gcarleo** [comment]
my take is that we should keep some internal naming consistency in netket, if we re-export this as part of netket.optimizer. Also, we have had for more than 2 years now netket.optimizer.Sgd and I think that changing to netket.optimizer.sgd is not really nice to people :) I would re-export it in a consistent way with our naming, and of course leave the possibility to use other optimizers outside of netket if needed... 

More broadly I think the issue is that PEP naming conventions do not address what happens when you use a function effectively as a class constructor... in that case you'd still name it as a function, but I'd argue that in fact that's just a way of constructing an object, so it should follow classes naming conventions? Anyways... it's a bit of bikeshedding, but my argument it's just a matter of internal consistency of the naming in netket

**Comment by gcarleo** [comment]
in my opinion since ```optax.sgd``` is constructing another object, it should just be called ```optax.Sgd```, also notice that in essentially ALL python frameworks optimizers are classes... (the only exceptions being jax and optax, but not flax)

**Comment by PhilipVinc** [comment]
BTW, in optax, `sgd(learning_rate=0.01, momentum=0, nesterov=False)` is also momentum and Nesterov, depending on how you change the parameters.

Defining `optimiser.Sgd=sgd()`, `optimiser.Momentum(lr, momentum=0.9)=sgd(lr, momentum)` as you'd want, it's gonna be _no changes_ to our existing API, but it also partly defeats the point of not getting code out of netket and relying on third-party libraries to do that for us (and better).

**Comment by gcarleo** [comment]
I understand, but still I find inconvenient that to do a simple optimizer (essentially 2 lines of code) you need to go look at the documentation of another project... ! of course if you want to add scheduling and other complicated things I agree with you...

**Comment by gcarleo** [comment]
Thank you @femtobit !

**Comment by gcarleo** [comment]
This looks very good now, I would merge it

**Review by femtobit — APPROVED** [review]

**Pull request merged**
