### PR TITLE
move special operators to their own file

### PR DESCRIPTION
**Pull request by PhilipVinc**
For my own reviewing sanity of the line of PRs opened by Dian, I want to move special operators to their own file first so the diff shows up nicely.

@wdphy16 please rebase your PRs on top of this?

### CODE REVIEW

**Comment by wdphy16** [comment]
I agree, and I think in this PR you can also move the tests like this commit https://github.com/netket/netket/pull/1335/commits/963e320ef0d71fb821cac9dfc049e7325dda5e20 , so the file structure of the tests is more consistent with that of the implementations. Currently `test_operator.py` just looks too long...

**Comment by PhilipVinc** [comment]
can you do it? feel free to push to this branch or create one on top of this.

**Comment by PhilipVinc** [comment]
Actually, just open a PR yourself with the commits in this branch plus reordering a bit the tests. I'll merge it quickly so you can rebase your other PRs.

**Comment by wdphy16** [comment]
Ok, let me do it

**Pull request closed without merging**
