### PR TITLE
Improve Qutip interoperability

### PR DESCRIPTION
**Pull request by PhilipVinc**
Adds conversion methods for `MCState` and `SuperOperators`

### CODE REVIEW

**Comment by gcarleo** [comment]
I like these but maybe we could make "convertors" to be stand-alone libraries instead of being in netket ?(we might have qiskit, cirq and other convertors too...)

**Comment by PhilipVinc** [comment]
The issue is that having `nkobj.to_qobj()` is only possible if we define it in netket itself, not in other packages.

And having a `nk_extensions.to_qutip(nkobj)` seems less nice?

**Comment by PhilipVinc** [comment]
I agree that eventually this could lead to an explosion of conversion methods. But hopefully i can manage to convicne qutip people to expose an interface so that objects can define themselves how to be converted.

A bit like we declare `__array_interface__` and it allows our lazy objects to be converted to matrices automatically, or our samplers to be converted to pytrees automatically. `np.array(lazy_qsr)` works: i'd like to also have `qutip.Qobj(nkobj)` work. Then we don't really care about defining those methods in netket itself or in a subpackage anymore...

(However I am experiencing high resistance from qutip people, who, for some reason, don't want to expose such a mechanism)

**Comment by femtobit** [comment]
> I like these but maybe we could make "convertors" to be stand-alone libraries instead of being in netket ?(we might have qiskit, cirq and other convertors too...)

It could help to put the conversion methods in a separate submodule, instead of making them class methods. For example, we could have
```python
operator_nk = nk.operator.Heisenberg(...)
operator_qt = nk.conversion.to_qutip(operator_nk)
```
and so on.

Whether this is beneficial or not depends on how many more conversions we plan to add in the future.

**Comment by gcarleo** [comment]
yes I see, definitely doing a common interface for all these objects would be ideal, but it seems really hard to come up with something that would work well for all relevant software unfortunately... (I mean, we can try, also with qiskit for example...). 

I think that @femtobit's suggestion is also good. In general, what I am afraid of is that we should start testing a lot of external packages and increase substantially the possible sources of incompatibilities/ need for future maintenance etc...

**Comment by PhilipVinc** [comment]
I'm personally not a fan of `operator_qt = nk.conversion.to_qutip(operator_nk)` because it is less discoverable and more boilerplatey.

Again, my plan is to have `qutip.Qobj(nk_obj)` work (so that, later on, we hopefully can get native access to all the plethora of schroedinger's equation solvers they do have). Though it will take a while and `to_qobj` is a stopgap.

As for increased testing effort and maintenance... well, yes. But we would have to test thoes methods anyway.
A separate package would indeed be nicer but i don't see an easy way to do it, unless @femtobit has ideas

**Comment by gcarleo** [comment]
would it be possible to estimate how long the running time of the tests gets with this PR?

**Comment by PhilipVinc** [comment]
Right now i'm not testing those methods.

Testing them would add basically 0 time (maybe 1-2 seconds?) of test time, and probably around 10-20 seconds of install time to install qutip too.

We could have a separate tester for that. But our issue for test time right now is stuff like QGT and correctedness tests of samplers.

**Comment by femtobit** [comment]
> I'm personally not a fan of `operator_qt = nk.conversion.to_qutip(operator_nk)` because it is less discoverable and more boilerplatey.

I tend to agree. I have no objection to a `to_qobj` method (also, libraries like pandas have all kinds of `to_something` methods as well, so its not like we're doing something particularly unusual here).

> But our issue for test time right now is stuff like QGT and correctedness tests of samplers.

That's true. Also some of the GCNN tests appear pretty high up in the list of runtimes now:
```
179.18s call     test/models/test_rbm.py::test_gcnn[fft-Square-autom-True]
137.40s call     test/models/test_rbm.py::test_gcnn[fft-Square-trans-True]
114.70s call     test/models/test_rbm.py::test_gcnn[fft-Chain-trans-True]
103.53s call     test/models/test_rbm.py::test_gcnn[fft-Chain-autom-True]
```
We should probably simplify this (maybe use smaller system sizes?) in a separate PR/issue.

**Comment by PhilipVinc** [comment]
Is this ok to merge then?

**Review by femtobit — APPROVED** [review]
Looks good to me.

**Pull request merged**
