### PR TITLE
Only check for `HaikuFramework` if haiku is loaded

### PR DESCRIPTION
**Pull request by femtobit**
Currently, using the `JaxFramework` model framework without haiku being installed causes an exception, because `HaikuFramework.is_my_module` (which tries to import haiku) is called anyways.

This PR fixes this by only checking for `haiku`-based modules if haiku is already loaded.

### CODE REVIEW

**Comment by femtobit** [comment]
The docstring tests fail because they try to import haiku and fail. I think the cleanest solutions are to either a) install haiku in the test environment (we should test `HaikuFramework` anyways) or b) have the docstrign test ignore the `model_frameworks.haiku` model.

What do you think?

**Review by gcarleo — APPROVED** [review]

**Review by PhilipVinc — CHANGES_REQUESTED** [review]
Can be done with a one liner

**Comment by femtobit** [comment]
As @PhilipVinc convinced me, it is sufficient for our purposes to check whether `haiku` is already loaded (instead of generally available), so I've updated the PR to this simplified case.

I've also added two tests: One that checks whether defining a `haiku` model actually works and one that tries to assert we are not trying to import `haiku` if we define a `jax`-based model. The later test is not perfect, as it will not error unless `HaikuFramework` is checked before `JaxFramework` here:
...
On my current system, `HaikuFramework` appears last in the list of frameworks and thus is never checked even before this PR. OTOH, I have seen this fail on another system, so I assume the order is non-deterministic and in any case it is good to have this sanity check, IMHO.

**Review by PhilipVinc — APPROVED** [review]

**Review by gcarleo — CHANGES_REQUESTED** [review]
jaxlib.xla_extension' has no attribute 'CompiledFunction

**Comment by femtobit** [comment]
The newest `haiku` is not compatible with the oldest JAX version we claim to support.

Maybe we should explicitly add a `netket[haiku]` feature to `setup.py` and make sure we specify a working version range? @PhilipVinc, what do you think?

**Comment by PhilipVinc** [comment]
The extra requirements should be for stuff you don't directly import (eg: tensorboard, that you never directly import but netket may import) not for stuff like haiku that the user importa directly, thus he is responsible for keeping at a synced version.

That said, I think we can just bump minimum jax required. I'll soon require flax 0.4/0.5 which also bumps jax. And recently a few bug fixes went in that are almost necessary in some cases.

**Review by gcarleo — APPROVED** [review]

**Pull request merged**
