### PR TITLE
port local operator to jax

### PR DESCRIPTION
**Pull request by inailuig**
Port I had done a long time ago. Should be thoroughly tested for correctness before use.

~Usage: Construct the numba `LocalOperator` first and then call `.to_jax_operator` on it.~

### CODE REVIEW

**Comment by PhilipVinc** [comment]
@inailuig I found a bug:

```python
import netket as nk
from netket.operator.boson import create as adag, destroy as a

hi = nk.hilbert.Fock(n_max=6, N=1)


H = -(
    1.0
    / 2.0
    * (
        adag(hi, 0, complex) * adag(hi, 0, complex)
        + a(hi, 0, complex) * a(hi, 0, complex)
    )
)


H_jax = H.to_jax_operator()

hd = H.to_dense()
hdj = H_jax.to_dense()
```

they dont match... could you take a look?

**Comment by PhilipVinc** [comment]
I think the problem is that it does not set to zero the 'extra' connected elements in the padded representation.

**Comment by PhilipVinc** [comment]
I added some more tests, fixed some stuff but more stuff is still broken...

**Comment by PhilipVinc** [comment]
The last remaining tests fail because we're checking that if we do `numba -> jax -> flatten -> unflatten -> numba ` we get the same thing. 

however, in the current implementation the flattening does not pass forward all internal fields, only the ones generated by setup, in order to avoid passing in extra fields to jax which are not jax arrays and would be unused anyways... And I do not want hashable arrays around because they would force extra recompilation

The correct solution would be to just disable reconversion to numba after unflattening...

**Comment by PhilipVinc** [comment]
unless you have better ideas?

**Comment by inailuig** [comment]
> unless you have better ideas?

one could extract it from the jax arrays (writing the inverse of pack_internals), but I doubt it's worth the effort...

**Comment by PhilipVinc** [comment]
not worth it indeed

**Review by PhilipVinc — APPROVED** [review]
thank you. Tests pass and it seems good now. If you like the solution I committed, please merge ahead!

**Pull request merged**
