### PR TITLE
Update abstract_variational_driver.py

### LINKED ISSUE #816: AbstractVariationalDriver.py bug in updating step_count
image

I think this error can be fixed either by writing a setter function for the `@property step_count` in the same way that `@optimizer.setter` exists in the same file. 

Otherwise, maybe this can be fixed by changing ` self.step_count = 0` to ` self._step_count = 0`.

image

### PR DESCRIPTION
**Pull request by evmckinney9**
fixes #816 
image

### CODE REVIEW

**Comment by PhilipVinc** [comment]
Please remove the setter

**Comment by evmckinney9** [comment]
> Please remove the setter

Will do, sorry was not sure which fix was better.

**Comment by evmckinney9** [comment]
I'm not sure what the mistake is in the formatting

**Review by PhilipVinc — APPROVED** [review]
thanks!

**Pull request merged**
