### PR TITLE
Revert #919 - sparse matrices in LocalOperator

### PR DESCRIPTION
**Pull request by PhilipVinc**
This PR reverts @VolodyaCO #919, which I have discussed with @femtobit .
I found two bugs in the last few days, due to that PR.
Moreover we keep seeing SciPy warnings that Localopeartor is changing the structure of sparse matrices which is slow.
While probably what #919 is doing is correct, we cannot have our standard code print out so many warnings because it's confusing to the user (he cannot do nothing about it, it's our inner code), and this should be fixed.

This PR readapts #964 because that was useful.

@VolodyaCO I'm sorry for reverting this but since we want to tag a new version tonight/tomorrow morning, I think that code is still too experimental and raising issues, while the old one was much more battle-tested.

I'll keep the code around in a branch so anybody who needs it can still access it.
If someone puts in the work necessary to get it up to a good level then we can merge it again.

### CODE REVIEW

**Comment by gcarleo** [comment]
what kind of bugs?

**Comment by PhilipVinc** [comment]
https://github.com/netket/netket/commit/7ac0f66aa4bb151ca930f3b68101126ed056068d 
#1039

**Comment by PhilipVinc** [comment]
To be fair, #919 also fixed a few bugs and #920 did speed up copying of operators.
So I slimmed down this PR to only revert the relevant part of 919 that is causing problems.

**Review by gcarleo — APPROVED** [review]

**Comment by VolodyaCO** [comment]
@PhilipVinc that's ok. What is the timeline for the localoperator refactor (implementing it in JAX)? There's still quite a bit of redundancy in the connected matrix elements for some applications that I'd like to take care of (also @fabienalet wants this), but I don't want to do that work if the localoperator JAX refactor is coming soon.

**Comment by VolodyaCO** [comment]
Also, @fabienalet, for your application you might want to use #919, otherwise you will run into memory issues.

**Comment by PhilipVinc** [comment]
> What is the timeline for the localoperator refactor (implementing it in JAX)

There is none. 
We are experimenting with it but it blows up compile times especially on GPU for dubious gains. Moreover, for some things we need the old numba version around so it's hard to find a good middle ground.
Moreover, I will now stop working myself on new features for a while unless there's an interesting project that requires it.

What can and should be done, not necessarily by me, is to split the _front end_ from the _back end_ of the LocalOperators: create a class that simply wraps the lazy kronecker product and only stores the `_operators` and `_acting_on` without generating all the `_x_prime`, `_mels` ecc, and then a second class that uses the information of the first to construct the stuff we need to index everything efficiently, but that does not allow mutation so it's easier to write.
This will also speed up manipulating those objects.

In any case, (1) if you want to use sparse matrices just revert the commit associated with this PR, https://github.com/netket/netket/commit/b79c1df6d696376329d3eba892746428735e151e .
(2) If you want to see the commit land again in master, somebody has to fix all the warnings that scipy spits out, and possibly investigate a better solution, and write some extra tests.
(3) I still don't see how using sparse matrices alleviates the exponential cost of LocalOpearots. In the best case scenario it reduces memory complexity by 33%, in normal scenarios by 0-10%. I'd love somebody to show me an example that proves me wrong.
(4) If your problem is repeated operators, probably sombedoy like splitting front end and back end and making everything immutable would fix your issue.

**Pull request merged**
