### PR TITLE
Attempt to fix #97 and setup.py debug mode

### LINKED ISSUE #97: Python bindings for Jastrow machines randomly failing
I realized in #91 that once in a while the python tests for the `Jastrow` machines fail. This issue seems related to some memory problem, but I still don't understand if it is on the c++ side or python

### PR DESCRIPTION
**Pull request by gcarleo**
Other attempt to fix #97 
Also change setup.py to easily accomodate debug options and sanitizer on Travis

### CODE REVIEW

**Comment by gcarleo** [comment]
@twesterhout  here there is also a small change to setup.py to have debug and sanitizer on Travis

The rest is my further attempts to fix #97 (now it seems to work, but it's a strange issue)

**Comment by gcarleo** [comment]
Please let's merge this to fix the CI problem. We can start using the new version of the setup.py once @twesterhout has done the final changes to his PR

**Comment by gcarleo** [comment]
@twesterhout is it OK now?

**Comment by twesterhout** [comment]
@gcarleo yes, thanks!

**Pull request merged**
