### PR TITLE
Ensure netket keeps working with last flax version (and fix tests that are broken)

### PR DESCRIPTION
**Pull request by PhilipVinc**
This is taken from #1547 , but does not switch our variational state away from frozen dict. 
Makes it easy to switch however.

I am unsure that we want to switch like flax (though many people have been confused about frozen dicts..)

### CODE REVIEW

**Comment by gcarleo** [comment]
> I am unsure that we want to switch like flax (though many people have been confused about frozen dicts..)

Personally I strongly dislike freezing, unfreezing and other similar stuff

**Comment by PhilipVinc** [comment]
it's because you're from the south

**Comment by PhilipVinc** [comment]
The problem is that without freezing one could do

```python
a = MCState(...)

pars = a.parameters
pars['Dense'] = my_array
```

and this will change the parameters in the state but we don't know it and will break some stuff.
The alternative would be to always return a copy of our parameters.

**Comment by PhilipVinc** [comment]
merging to fix tests. Discussion on freezing and unfreezing will be in the actual PR with changes #1547

**Pull request merged**
