### PR TITLE
Make create_RBMSymm internal

### PR DESCRIPTION
**Pull request by femtobit**
As discussed in https://github.com/netket/netket/pull/573#discussion_r600392216.

### CODE REVIEW

**Comment by PhilipVinc** [comment]
I'm curious of how the docstring will get rendered by sphinx.
I think he'll make a mess

**Comment by femtobit** [comment]
@PhilipVinc Yes, definitely... I cannot emulate how the attributes are rendered on the machine, so probably we'd need to put the full docstring with all attributes on the function.

**Comment by PhilipVinc** [comment]
Yeah it's rather messy.
Let's just copy paste all attributes.

**Review by gcarleo — APPROVED** [review]

**Review by PhilipVinc — CHANGES_REQUESTED** [review]
Docstrings with attributes on the create_RBMSymm

**Review by PhilipVinc — APPROVED** [review]

**Comment by PhilipVinc** [comment]
great, thanks!

**Pull request merged**
